registerUser(S$.assume(ownerEmail0),var var var var var  = S$.symbol(,"") = S$.symbol(var  = S$.symbol(,""),"") = S$.symbol(var var  = S$.symbol(,"") = S$.symbol(var  = S$.symbol(,""),""),"") = S$.symbol(var var var  = S$.symbol(,"") = S$.symbol(var  = S$.symbol(,""),"") = S$.symbol(var var  = S$.symbol(,"") = S$.symbol(var  = S$.symbol(,""),""),""),"") = S$.symbol(var var var var  = S$.symbol(,"") = S$.symbol(var  = S$.symbol(,""),"") = S$.symbol(var var  = S$.symbol(,"") = S$.symbol(var  = S$.symbol(,""),""),"") = S$.symbol(var var var  = S$.symbol(,"") = S$.symbol(var  = S$.symbol(,""),"") = S$.symbol(var var  = S$.symbol(,"") = S$.symbol(var  = S$.symbol(,""),""),""),""),""),,,)
login(S$.assume(ownerEmail1),var var S$.assert(ownerEmail0) = S$.symbol(S$.assert(ownerEmail0),"") = S$.symbol(var S$.assert(ownerEmail0) = S$.symbol(S$.assert(ownerEmail0),""),""))
createRestaurant(S$.assume(token_present(var S$.assert(ownerEmail1) = S$.symbol(S$.assert(ownerEmail1),""))))
updateRestaurant(S$.assume(token_present(var S$.assert(restaurantName2) = S$.symbol(S$.assert(restaurantName2),""))))
S$.assume(token_present(S$.assert(restaurantId3)))
S$.assert(viewOrders())
