/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
const superagent = require("superagent");
const EM = require("./EMTestUtils.js");
jest.setTimeout(60000);




/**
*  This file was automatically generated by EvoMaster on 2026-05-13T21:47:49.780470+05:30[Asia/Kolkata]
*  
*  The generated test suite contains 12 tests
*  
*  Covered targets: 36
*  
*  Used time: 0h 1m 0s
*  
*  Needed budget for current results: 15%
*  
*  This file contains test cases that represent successful calls.
*  
*/

const baseUrlOfSut = "http://localhost:3001";


beforeAll( async () => {
});








/**
* Calls:
* (204) OPTIONS:/api/trips
*/
test("test_0_OptionsOnTripsReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/trips").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/trips/search-user
*/
test("test_1_OptionsOnSearch_userReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/trips/search-user").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/trips/{tripId}
*/
test("test_2_OptionsOnApiTripReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/trips/lLr9ogS6tc").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/expenses/{expenseId}
*/
test("test_3_OptionsOnExpensReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/expenses/KyUVH5Wrc").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/trips/{tripId}/members
*/
test("test_4_OptionsOnMembersReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/trips/K_7kaaXlp2dg/members").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/trips/join/{inviteCode}
*/
test("test_5_OptionsOnJoinReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/trips/join/081p_UjW0jy9nh").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/expenses/trip/{tripId}
*/
test("test_6_OptionsOnExpensesTripReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/expenses/trip/1P0De1IG").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/proposals/trip/{tripId}
*/
test("test_7_OptionsOnProposalsTripReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/proposals/trip/iqx9Jn").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/captures/trip/{tripId}
*/
test("test_8_OptionsOnCapturesTripReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/captures/trip/TYN_rV9RZIKHgo_j").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/trips/{tripId}/members/{memberId}
*/
test("test_9_OptionsOnMemberReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/trips/gQn/members/8pPi52Z_6kowX5G").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/expenses/trip/{tripId}/statistics
*/
test("test_10_OptionsOnStatisticsReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/expenses/trip/mdIGMhgXNNk/statistics").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/expenses/trip/{tripId}/balance
*/
test("test_11_OptionsOnBalanceReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/expenses/trip/p6s9XRDTLlZly/balance").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});
