/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
const superagent = require("superagent");
const EM = require("./EMTestUtils.js");
jest.setTimeout(60000);




/**
*  This file was automatically generated by EvoMaster on 2026-05-13T21:47:49.765234+05:30[Asia/Kolkata]
*  
*  The generated test suite contains 19 tests
*  
*  Covered targets: 63
*  
*  Used time: 0h 1m 0s
*  
*  Needed budget for current results: 15%
*  
*  This file contains test cases that are likely to indicate faults.
*  
*/

const baseUrlOfSut = "http://localhost:3001";


beforeAll( async () => {
});








/**
* Calls:
* (401) GET:/api/trips
* Found 1 potential fault of type-code 101
*/
test("test_0_GetOnTripsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/trips'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/trips").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) POST:/api/trips
* Found 1 potential fault of type-code 101
* Using 1 example:
*   (-) BODY -> Paris Adventure
*/
test("test_1_PostOnTripsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/trips").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"name\" : \"Paris Adventure\", " + 
                " \"startDate\" : \"2092-00-08\", " + 
                " \"endDate\" : \"1921-09-19\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) GET:/api/trips/{tripId}
* Found 1 potential fault of type-code 101
*/
test("test_2_GetOnApiTripReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/trips/{tripId}'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/trips/0qz2VbC8oZ1IAs3w").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) GET:/api/trips/search-user
* Found 1 potential fault of type-code 101
*/
test("test_3_GetOnTripsSearch_userReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/trips/search-user'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/trips/search-user").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) GET:/api/trips/search-user
* Found 1 potential fault of type-code 101
*/
test("test_4_GetOnTripsSearch_userWithQueryparamReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/trips/search-user'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/trips/search-user?email=1B").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) PUT:/api/expenses/{expenseId}
* Found 1 potential fault of type-code 101
*/
test("test_5_PutOnExpensReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/expenses/{expenseId}'.
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/expenses/IKoiH5B2SLgLvEW2").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"title\" : \"SR\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) PUT:/api/trips/{tripId}
* Found 1 potential fault of type-code 101
*/
test("test_6_PutOnTripReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/trips/{tripId}'.
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/trips/uvl7hNA").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) DELETE:/api/expenses/{expenseId}
* Found 1 potential fault of type-code 101
*/
test("test_7_DeleteOnExpensReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/expenses/{expenseId}'.
    const res_0 = await superagent
            .delete(baseUrlOfSut + "/api/expenses/s").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) DELETE:/api/trips/{tripId}
* Found 1 potential fault of type-code 101
*/
test("test_8_DeleteOnTripReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/trips/{tripId}'.
    const res_0 = await superagent
            .delete(baseUrlOfSut + "/api/trips/ix").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) GET:/api/captures/trip/{tripId}
* Found 1 potential fault of type-code 101
*/
test("test_9_GetOnCapturesTripReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/captures/trip/{tripId}'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/captures/trip/CN1wM4jxHIbkSV3_").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) GET:/api/proposals/trip/{tripId}
* Found 1 potential fault of type-code 101
*/
test("test_10_GetOnProposalsTripReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/proposals/trip/{tripId}'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/proposals/trip/73TZv1").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) GET:/api/expenses/trip/{tripId}
* Found 1 potential fault of type-code 101
*/
test("test_11_GetOnExpensesTripReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/expenses/trip/{tripId}'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/expenses/trip/AxfFPXuob5hHUNT").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) POST:/api/proposals/trip/{tripId}
* Found 1 potential fault of type-code 101
*/
test("test_12_PostOnProposalsTripReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/proposals/trip/{tripId}'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/proposals/trip/ElFgYcL_3").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"title\" : \"b2NTCU\", " + 
                " \"type\" : \"poll\", " + 
                " \"description\" : \"jNGN1i\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) POST:/api/expenses/trip/{tripId}
* Found 1 potential fault of type-code 101
*/
test("test_13_PostOnExpensesTripReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/expenses/trip/{tripId}'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/expenses/trip/8aOw").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"title\" : \"VejsA\", " + 
                " \"amount\" : 1.327811652656908E9, " + 
                " \"category\" : \"qbFWLQ7M\", " + 
                " \"description\" : \"JP9LV\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) POST:/api/trips/join/{inviteCode}
* Found 1 potential fault of type-code 101
*/
test("test_14_PostOnJoinReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/trips/join/{inviteCode}'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/trips/join/R").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) POST:/api/trips/{tripId}/members
* Found 1 potential fault of type-code 101
*/
test("test_15_PostOnMembersReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/trips/{tripId}/members'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/trips/fqT_jN17Bo_Q/members").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) GET:/api/expenses/trip/{tripId}/balance
* Found 1 potential fault of type-code 101
*/
test("test_16_GetOnBalanceReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/expenses/trip/{tripId}/balance'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/expenses/trip/4HQ_i/balance").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) GET:/api/expenses/trip/{tripId}/statistics
* Found 1 potential fault of type-code 101
*/
test("test_17_GetOnStatisticsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/expenses/trip/{tripId}/statistics'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/expenses/trip/H_9u/statistics").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) DELETE:/api/trips/{tripId}/members/{memberId}
* Found 1 potential fault of type-code 101
*/
test("test_18_DeleteOnMemberReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/trips/{tripId}/members/{memberId}'.
    const res_0 = await superagent
            .delete(baseUrlOfSut + "/api/trips/qnV/members/nmUHbVW2Sw3Ou7").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Unauthorized");
});
