/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
const superagent = require("superagent");
const EM = require("./EMTestUtils.js");
jest.setTimeout(60000);




/**
*  This file was automatically generated by EvoMaster on 2026-05-13T21:37:37.418659+05:30[Asia/Kolkata]
*  
*  The generated test suite contains 15 tests
*  
*  Covered targets: 45
*  
*  Used time: 0h 2m 0s
*  
*  Needed budget for current results: 17%
*  
*  This file contains test cases that represent successful calls.
*  
*/

const baseUrlOfSut = "http://localhost:3000";


beforeAll( async () => {
});








/**
* Calls:
* (204) OPTIONS:/api/products
*/
test("test_0_OptionsOnProductsReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/products").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/cart
*/
test("test_1_OptionsOnCartReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/cart").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/orders
*/
test("test_2_OptionsOnOrdersReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/orders").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/reviews
*/
test("test_3_OptionsOnReviewsReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/reviews").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/auth/register
*/
test("test_4_OptionsOnRegisterReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/auth/register").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/auth/login
*/
test("test_5_OptionsOnLoginReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/auth/login").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/auth/profile
*/
test("test_6_OptionsOnProfileReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/auth/profile").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/products/{id}
*/
test("test_7_OptionsOnProductReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/products/8BOTofZHu49mUS").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/cart/add
*/
test("test_8_OptionsOnAddReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/cart/add").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/cart/update
*/
test("test_9_OptionsOnUpdateReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/cart/update").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/orders/buyer
*/
test("test_10_OptionsOnBuyerReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/orders/buyer").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/orders/seller
*/
test("test_11_OptionsOnSellerReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/orders/seller").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/reviews/{id}
*/
test("test_12_OptionsOnReviewReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/reviews/1krXvTortLoFg6r").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/products/seller/inventory
*/
test("test_13_OptionsOnInventoryReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/products/seller/inventory").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/orders/{id}/status
*/
test("test_14_OptionsOnStatusReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/orders/ZJu0jx5YMb5mtaA/status").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});
