/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
const superagent = require("superagent");
const EM = require("./EMTestUtils.js");
jest.setTimeout(60000);




/**
*  This file was automatically generated by EvoMaster on 2026-05-13T21:37:37.403686+05:30[Asia/Kolkata]
*  
*  The generated test suite contains 21 tests
*  
*  Covered targets: 88
*  
*  Used time: 0h 2m 0s
*  
*  Needed budget for current results: 17%
*  
*  This file contains test cases that are likely to indicate faults.
*  
*/

const baseUrlOfSut = "http://localhost:3000";


beforeAll( async () => {
});








/**
* Calls:
* (500) POST:/api/reviews
* Found 2 potential faults. Type-codes: 100, 101
*/
test("test_0_PostOnReviewsShowsfaults_100_101", async () => {
    
    // Fault100. HTTP Status 500.
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/api/reviews'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/reviews").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"productId\" : \"GVWoX\", " + 
                " \"orderId\" : \"45_Js\", " + 
                " \"rating\" : 5, " + 
                " \"comment\" : \"OiBdJP1QEPfOdw\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(500);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Cannot read properties of undefined (reading '_id')");
});


/**
* Calls:
* (200) GET:/api/products
* Found 1 potential fault of type-code 101
*/
test("test_1_GetOnProductsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/products").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.products.length).toBe(0);
    expect(res_0.body.currentPage).toBe(1);
    expect(res_0.body.totalPages).toBe(0);
    expect(res_0.body.totalProducts).toBe(0);
});


/**
* Calls:
* (401) GET:/api/cart
* Found 1 potential fault of type-code 101
*/
test("test_2_GetOnCartReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/cart'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/cart").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Access token required");
});


/**
* Calls:
* (401) POST:/api/orders
* Found 1 potential fault of type-code 101
* Using 2 examples:
*   (-) BODY -> 123 Main St
*   (-) BODY -> card
*/
test("test_3_PostOnOrdersReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/orders'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/orders").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"shippingAddress\" : \"123 Main St\", " + 
                " \"paymentMethod\" : \"card\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Access token required");
});


/**
* Calls:
* (401) POST:/api/products
* Found 1 potential fault of type-code 101
* Using 5 examples:
*   (-) BODY -> 100
*   (-) BODY -> 29.99
*   (-) BODY -> A great product
*   (-) BODY -> Electronics
*   (-) BODY -> Sample Product
*/
test("test_4_PostOnProductsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/products'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/products").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"title\" : \"Sample Product\", " + 
                " \"description\" : \"A great product\", " + 
                " \"category\" : \"Electronics\", " + 
                " \"price\" : 29.99, " + 
                " \"quantity\" : 100 " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Access token required");
});


/**
* Calls:
* (500) GET:/api/products/{id}
* Found 2 potential faults. Type-codes: 100, 101
*/
test("test_5_GetOnProductShowsfaults_100_101", async () => {
    
    // Fault100. HTTP Status 500.
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/api/products/{id}'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/products/4p367r3nz").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(500);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Cast to ObjectId failed for value \"4p367r3nz\" (type string) at path \"_id\" for model \"Product\"");
});


/**
* Calls:
* (200) GET:/api/reviews/{id}
* Found 1 potential fault of type-code 101
*/
test("test_6_GetOnReviewReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/reviews/BHlDTPjft").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.reviews.length).toBe(0);
    expect(res_0.body.averageRating).toBe(0);
    expect(res_0.body.totalReviews).toBe(0);
});


/**
* Calls:
* (400) POST:/api/auth/register
* Found 1 potential fault of type-code 101
* Using 3 examples:
*   (-) BODY -> Alice Smith
*   (-) BODY -> Password1!
*   (-) BODY -> alice@example.com
*/
test("test_7_PostOnRegisterReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/auth/register").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"fullName\" : \"Alice Smith\", " + 
                " \"email\" : \"alice@example.com\", " + 
                " \"password\" : \"Password1!\", " + 
                " \"userType\" : \"EVOMASTER\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(400);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("User already exists");
});


/**
* Calls:
* (400) POST:/api/auth/login
* Found 1 potential fault of type-code 101
*/
test("test_8_PostOnLoginReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/api/auth/login'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/auth/login").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"email\" : \"\", " + 
                " \"password\" : \"TfjY4GlufpBEeS\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(400);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Missing required fields: email");
});


/**
* Calls:
* (401) GET:/api/orders/seller
* Found 1 potential fault of type-code 101
*/
test("test_9_GetOnSellerReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/orders/seller'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/orders/seller").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Access token required");
});


/**
* Calls:
* (401) GET:/api/orders/buyer
* Found 1 potential fault of type-code 101
*/
test("test_10_GetOnBuyerReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/orders/buyer'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/orders/buyer").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Access token required");
});


/**
* Calls:
* (401) GET:/api/auth/profile
* Found 1 potential fault of type-code 101
*/
test("test_11_GetOnProfileReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/auth/profile").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Access token required");
});


/**
* Calls:
* (401) POST:/api/cart/add
* Found 1 potential fault of type-code 101
* Using 1 example:
*   (-) BODY -> 1
*/
test("test_12_PostOnAddReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/cart/add'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/cart/add").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"productId\" : \"\", " + 
                " \"quantity\" : 1 " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Access token required");
});


/**
* Calls:
* (401) POST:/api/auth/login
* Found 1 potential fault of type-code 101
*/
test("test_13_PostOnLoginReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/auth/login").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"email\" : \"s\", " + 
                " \"password\" : \"GKnwwR\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Invalid credentials");
});


/**
* Calls:
* (401) PUT:/api/cart/update
* Found 1 potential fault of type-code 101
*/
test("test_14_PutOnUpdateReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/cart/update'.
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/cart/update").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"productId\" : \"VffOQ\", " + 
                " \"quantity\" : 757 " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Access token required");
});


/**
* Calls:
* (401) PUT:/api/products/{id}
* Found 1 potential fault of type-code 101
*/
test("test_15_PutOnProductReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/products/{id}'.
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/products/Zj1g7").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Access token required");
});


/**
* Calls:
* (401) PUT:/api/auth/profile
* Found 1 potential fault of type-code 101
*/
test("test_16_PutOnProfileReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/auth/profile'.
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/auth/profile").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"address\" : \"\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Access token required");
});


/**
* Calls:
* (401) DELETE:/api/products/{id}
* Found 1 potential fault of type-code 101
*/
test("test_17_DeleteOnProductReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/products/{id}'.
    const res_0 = await superagent
            .delete(baseUrlOfSut + "/api/products/q6VGhhFT").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Access token required");
});


/**
* Calls:
* (404) GET:/api/products/{id}
* Found 1 potential fault of type-code 101
*/
test("test_18_GetOnProductReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/products/Vkoro3tvkQ3A").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(404);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Product not found");
});


/**
* Calls:
* (401) GET:/api/products/seller/inventory
* Found 1 potential fault of type-code 101
*/
test("test_19_GetOnInventoryReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/products/seller/inventory'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/products/seller/inventory").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Access token required");
});


/**
* Calls:
* (401) PUT:/api/orders/{id}/status
* Found 1 potential fault of type-code 101
*/
test("test_20_PutOnStatusReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/api/orders/{id}/status'.
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/orders/3CDKgKsTMovDeeA/status").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"status\" : \"shipped\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.error).toBe("Access token required");
});
