/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
const superagent = require("superagent");
const EM = require("./EMTestUtils.js");
jest.setTimeout(60000);




/**
*  This file was automatically generated by EvoMaster on 2026-05-13T21:45:50.814342+05:30[Asia/Kolkata]
*  
*  The generated test suite contains 45 tests
*  
*  Covered targets: 90
*  
*  Used time: 0h 2m 0s
*  
*  Needed budget for current results: 30%
*  
*  This file contains test cases that represent failed calls, but not indicative of faults.
*  
*/

const baseUrlOfSut = "http://localhost:8083";


beforeAll( async () => {
});








/**
* Calls:
* (403) OPTIONS:/api/messages
*/
test("test_0_OptionsOnMessagesReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/messages").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/bookings
*/
test("test_1_OptionsOnApiBookingsReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/bookings").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/notifications
*/
test("test_2_OptionsOnNotificationsReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/notifications").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/listings
*/
test("test_3_OptionsOnApiListingsReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/listings").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/categories
*/
test("test_4_OptionsOnApiCategoriesReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/categories").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/reviews/{id}
*/
test("test_5_OptionsOnApiReviewReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/reviews/Uij0s").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/providers/profile
*/
test("test_6_OptionsOnProvidersProfileReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/providers/profile").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/providers/listings
*/
test("test_7_OptionsOnProvidersListingsReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/providers/listings").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/notifications/read-all
*/
test("test_8_OptionsOnRead_allReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/notifications/read-all").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/notifications/admin
*/
test("test_9_OptionsOnAdminReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/notifications/admin").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/categories
*/
test("test_10_OptionsOnAdminCategoriesReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/categories").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/provider/bookings
*/
test("test_11_OptionsOnProviderBookingsReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/provider/bookings").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/messages/thread
*/
test("test_12_OptionsOnThreadReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/messages/thread").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/messages/conversations
*/
test("test_13_OptionsOnConversationsReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/messages/conversations").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/listings/{id}
*/
test("test_14_OptionsOnApiListReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/listings/ohqT2n2wbqAkpaY").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/bookings/{id}
*/
test("test_15_OptionsOnApiBookReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/bookings/GKZO3FDR5Hy").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/bookings/my
*/
test("test_16_OptionsOnMyReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/bookings/my").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/users
*/
test("test_17_OptionsOnUsersReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/users").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/reviews
*/
test("test_18_OptionsOnAdminReviewsReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/reviews").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/listings
*/
test("test_19_OptionsOnAdminListingsReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/listings").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/dashboard
*/
test("test_20_OptionsOnDashboardReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/dashboard").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/bookings
*/
test("test_21_OptionsOnAdminBookingsReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/bookings").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/providers/profile/me
*/
test("test_22_OptionsOnMeReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/providers/profile/me").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/providers/listings/{id}
*/
test("test_23_OptionsOnProvidersListReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/providers/listings/ISBFyNWd0U9jyLcS").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/categories/{id}
*/
test("test_24_OptionsOnCategoriReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/categories/8znxt7").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/notifications/{id}/read
*/
test("test_25_OptionsOnReadReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/notifications/YTkrc/read").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/bookings/{id}/confirm
*/
test("test_26_OptionsOnConfirmReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/bookings/IpN3Z/confirm").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/bookings/{id}/complete
*/
test("test_27_OptionsOnCompleteReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/bookings/Q4T/complete").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/bookings/{id}/cancel
*/
test("test_28_OptionsOnCancelReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/bookings/F_CTYkaCoyP/cancel").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/bookings/{bookingId}/reviews
*/
test("test_29_OptionsOnBookReviewsReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/bookings/W3X_Jy1wgIV13YGZ/reviews").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/providers/{providerId}/reviews
*/
test("test_30_OptionsOnProvidReviewsReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/providers/v/reviews").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/providers/{providerId}/profile
*/
test("test_31_OptionsOnProvidProfileReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/providers/AdpOFFkLzwkOZ/profile").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/provider/bookings/{id}
*/
test("test_32_OptionsOnProviderBookReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/provider/bookings/64q5LI1htE_VL").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/listings/{listingId}/reviews
*/
test("test_33_OptionsOnListReviewsReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/listings/pXLuRg4Hh0/reviews").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/users/{id}
*/
test("test_34_OptionsOnUserReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/users/nJlA4FJWX").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/analytics/top-providers
*/
test("test_35_OptionsOnTop_providersReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/analytics/top-providers").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/analytics/top-categories
*/
test("test_36_OptionsOnTop_categoriesReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/analytics/top-categories").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/analytics/summary
*/
test("test_37_OptionsOnSummaryReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/analytics/summary").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/analytics/bookings-over-time
*/
test("test_38_OptionsOnBookings_over_timeReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/analytics/bookings-over-time").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/reviews/{id}
*/
test("test_39_OptionsOnAdminReviewReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/reviews/jUm").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/providers/listings/{id}/photos
*/
test("test_40_OptionsOnPhotosReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/providers/listings/3K0/photos").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/bookings/{id}/cancel
*/
test("test_41_OptionsOnCancelReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/bookings/FmZXVkO0BAYW/cancel").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/users/{id}/status
*/
test("test_42_OptionsOnUserStatusReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/users/Vt13X6k/status").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/admin/listings/{id}/status
*/
test("test_43_OptionsOnListStatusReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/admin/listings/PbPTq/status").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) OPTIONS:/api/providers/listings/{id}/photos/{photoId}
*/
test("test_44_OptionsOnPhotoReturns403", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/providers/listings/aYeu0OSWBTQ/photos/q0WiE6lDMlIouy").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});
