/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
const superagent = require("superagent");
const EM = require("./EMTestUtils.js");
jest.setTimeout(60000);




/**
*  This file was automatically generated by EvoMaster on 2026-05-13T21:45:50.794987+05:30[Asia/Kolkata]
*  
*  The generated test suite contains 79 tests
*  
*  Covered targets: 227
*  
*  Used time: 0h 2m 0s
*  
*  Needed budget for current results: 30%
*  
*  This file contains test cases that are likely to indicate faults.
*  
*/

const baseUrlOfSut = "http://localhost:8083";


beforeAll( async () => {
});








/**
* Calls:
* (403) GET:/api/notifications
* Found 1 potential fault of type-code 101
*/
test("test_0_GetOnApiNotificationsWithQueryparamsIsreadNegativeSizeReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/notifications'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/notifications?" + 
                "isRead=true&" + 
                "page=782&" + 
                "size=-1907429915").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/notifications
* Found 1 potential fault of type-code 101
*/
test("test_1_GetOnNotificationsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/notifications'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/notifications?" + 
                "page=560101305&" + 
                "size=742").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/notifications
* Found 1 potential fault of type-code 101
*/
test("test_2_GetOnNotificationsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/notifications'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/notifications?" + 
                "isRead=true&" + 
                "page=222&" + 
                "size=1738962567").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/notifications
* Found 1 potential fault of type-code 101
*/
test("test_3_GetOnNotificationsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/notifications'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/notifications?" + 
                "isRead=true&" + 
                "size=714").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/messages
* Found 1 potential fault of type-code 101
*/
test("test_4_GetOnMessagesReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/messages'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/messages").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/notifications
* Found 1 potential fault of type-code 101
*/
test("test_5_GetOnNotificationsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/notifications'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/notifications?" + 
                "isRead=true&" + 
                "page=261").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/notifications
* Found 1 potential fault of type-code 101
*/
test("test_6_GetOnNotificationsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/notifications'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/notifications?" + 
                "isRead=false&" + 
                "page=474&" + 
                "size=279").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/notifications
* Found 1 potential fault of type-code 101
*/
test("test_7_GetOnNotificationsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/notifications'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/notifications?" + 
                "isRead=false&" + 
                "page=320&" + 
                "size=20").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/notifications
* Found 1 potential fault of type-code 101
*/
test("test_8_GetOnNotificationsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/notifications'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/notifications?" + 
                "isRead=true&" + 
                "page=0&" + 
                "size=215").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/notifications
* Found 1 potential fault of type-code 101
*/
test("test_9_GetOnApiNotificationsWithQueryparamsIsreadNegativePageReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/notifications'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/notifications?" + 
                "isRead=true&" + 
                "page=-717123453&" + 
                "size=30").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/bookings
* Found 1 potential fault of type-code 101
*/
test("test_10_PostOnBookingsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/bookings'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/bookings").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"serviceListingId\" : \"8u8zB\", " + 
                " \"scheduledAt\" : \"2063-02-28T01:52:43Z\", " + 
                " \"notes\" : \"ARaY\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/messages
* Found 1 potential fault of type-code 101
*/
test("test_11_PostOnMessagesReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/messages'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/messages").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"toUserId\" : \"Jm\", " + 
                " \"bookingId\" : \"dbuyjbts\", " + 
                " \"serviceListingId\" : \"N7\", " + 
                " \"content\" : \"zDM\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (200) POST:/api/auth/logout
* Found 1 potential fault of type-code 101
*/
test("test_12_PostOnLogoutReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type [Path '/data'] Instance type (null) does not match any allowed primitive type (allowed: ["object"])
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/auth/logout").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(true);
    expect(res_0.body.message).toBe("Logged out successfully");
    expect(res_0.body.data).toBe(null);
});


/**
* Calls:
* (400) POST:/api/auth/login
* Found 1 potential fault of type-code 101
*/
test("test_13_PostOnAuthLoginReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/api/auth/login'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/auth/login").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"email\" : \"DIIal5oWOr92C7\", " + 
                " \"password\" : \"QzwN_5Ofl3fHQo6\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(400);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Validation failed");
    expect(res_0.body.errors.email).toBe("Email should be valid");
});


/**
* Calls:
* (400) POST:/api/auth/signup
* Found 1 potential fault of type-code 101
*/
test("test_14_PostOnSignupReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/api/auth/signup'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/auth/signup").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"email\" : \"\", " + 
                " \"password\" : \"F8UVjL\", " + 
                " \"role\" : \"prefix_PROVIDER\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(400);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Validation failed");
    expect(res_0.body.errors.role).toBe("Role must be either USER or PROVIDER");
    expect(res_0.body.errors.email).toBe("Email is required");
});


/**
* Calls:
* (400) POST:/api/test/register
* Found 1 potential fault of type-code 101
*/
test("test_15_PostOnRegisterReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/api/test/register'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/test/register").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"7qYp4U1K4wy28\" : \"a5GfGPw\", " + 
                " \"r8SPdvvZf9undC\" : \"i9fVuQh\", " + 
                " \"cpgiCoKb\" : \"BbXVSADILyzWhLI\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(400);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/bookings
* Found 1 potential fault of type-code 101
*/
test("test_16_GetOnAdminBookingsWithQueryparamReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/bookings'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/bookings?status=xBys2LXu6TYM").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/dashboard
* Found 1 potential fault of type-code 101
*/
test("test_17_GetOnDashboardReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/dashboard'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/dashboard").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/listings
* Found 1 potential fault of type-code 101
*/
test("test_18_GetOnAdminListingsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/listings'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/listings").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/reviews
* Found 1 potential fault of type-code 101
*/
test("test_19_GetOnAdminReviewsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/reviews'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/reviews").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/users
* Found 1 potential fault of type-code 101
*/
test("test_20_GetOnAdminUsersWithQueryparamReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/users'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/users?role=0e8ZK4SgzLOppTd").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/bookings/my
* Found 1 potential fault of type-code 101
*/
test("test_21_GetOnMyReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/bookings/my'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/bookings/my").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/bookings/{id}
* Found 1 potential fault of type-code 101
*/
test("test_22_GetOnApiBookReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/bookings/{id}'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/bookings/Ki").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/messages/conversations
* Found 1 potential fault of type-code 101
*/
test("test_23_GetOnConversationsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/messages/conversations'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/messages/conversations").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/messages/thread
* Found 1 potential fault of type-code 101
*/
test("test_24_GetOnThreadReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/messages/thread'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/messages/thread?bookingId=3s65HLEAIEsUv_0").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/provider/bookings
* Found 1 potential fault of type-code 101
*/
test("test_25_GetOnProviderBookingsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/provider/bookings'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/provider/bookings").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/categories
* Found 1 potential fault of type-code 101
*/
test("test_26_GetOnCategoriesReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/categories'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/categories").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/providers/listings
* Found 1 potential fault of type-code 101
*/
test("test_27_GetOnProvidersListingsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/providers/listings'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/providers/listings").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/bookings
* Found 1 potential fault of type-code 101
*/
test("test_28_GetOnAdminBookingsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/bookings'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/bookings").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/listings
* Found 1 potential fault of type-code 101
*/
test("test_29_GetOnAdminListingsWithQueryparamReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/listings'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/listings?categoryId=YeQzi_bGKiZBe").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/users
* Found 1 potential fault of type-code 101
*/
test("test_30_GetOnAdminUsersReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/users'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/users").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/admin/categories
* Found 1 potential fault of type-code 101
*/
test("test_31_PostOnCategoriesReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/categories'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/admin/categories").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"name\" : \"1qGFYW\", " + 
                " \"description\" : \"y7bTHvCw\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/notifications/admin
* Found 1 potential fault of type-code 101
*/
test("test_32_PostOnAdminReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/notifications/admin'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/notifications/admin").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"targetType\" : \"9L\", " + 
                " \"title\" : \"Zk4kMNZBnXZ\", " + 
                " \"message\" : \"zCyr5nxj50NZ7JY\", " + 
                " \"type\" : \"BOOKING_CREATED\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/notifications/read-all
* Found 1 potential fault of type-code 101
*/
test("test_33_PostOnRead_allReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/notifications/read-all'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/notifications/read-all").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/providers/listings
* Found 1 potential fault of type-code 101
*/
test("test_34_PostOnListingsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/providers/listings'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/providers/listings").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"categoryId\" : \"RtMAycVKvU\", " + 
                " \"title\" : \"8QwzrRABnE\", " + 
                " \"description\" : \"p2ubrvJirKorU\", " + 
                " \"price\" : -3.42165489220072E8, " + 
                " \"location\" : \"JWKZTmkymTy\", " + 
                " \"estimatedDuration\" : 520 " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/providers/profile
* Found 1 potential fault of type-code 101
*/
test("test_35_PostOnProfileReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/providers/profile'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/providers/profile").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"displayName\" : \"QBUGu4Srk\", " + 
                " \"phone\" : \"2EXzp2GZQtvk\", " + 
                " \"additionalContacts\" : \"ZiQhkgHF\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) PUT:/api/reviews/{id}
* Found 1 potential fault of type-code 101
*/
test("test_36_PutOnReviewReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/reviews/{id}'.
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/reviews/eGYg8SUilgoSM8").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"rating\" : 1, " + 
                " \"comment\" : \"B7_\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) DELETE:/api/reviews/{id}
* Found 1 potential fault of type-code 101
*/
test("test_37_DeleteOnApiReviewReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/reviews/{id}'.
    const res_0 = await superagent
            .delete(baseUrlOfSut + "/api/reviews/7TnCWlRqmhwCu_0").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (404) GET:/api/listings/{id}
* Found 1 potential fault of type-code 101
*/
test("test_38_GetOnListReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/api/listings/{id}'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/listings/N2QZMe4IA6ea0Q").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(404);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Service listing not found");
    expect(res_0.body.data).toBe(null);
});


/**
* Calls:
* (400) POST:/api/auth/admin/login
* Found 1 potential fault of type-code 101
*/
test("test_39_PostOnAdminLoginReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/api/auth/admin/login'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/auth/admin/login").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"email\" : \"zhlt2ZYhY\", " + 
                " \"password\" : \"FClTy5jq0U2NXP\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(400);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Validation failed");
    expect(res_0.body.errors.email).toBe("Email should be valid");
});


/**
* Calls:
* (403) GET:/api/admin/analytics/bookings-over-time
* Found 1 potential fault of type-code 101
*/
test("test_40_GetOnBookings_over_timeReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/analytics/bookings-over-time'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/analytics/bookings-over-time?days=152").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/analytics/bookings-over-time
* Found 1 potential fault of type-code 101
*/
test("test_41_GetOnAnalyticsBookings_over_timeReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/analytics/bookings-over-time'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/analytics/bookings-over-time").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/analytics/summary
* Found 1 potential fault of type-code 101
*/
test("test_42_GetOnSummaryReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/analytics/summary'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/analytics/summary").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/analytics/top-categories
* Found 1 potential fault of type-code 101
*/
test("test_43_GetOnTop_categoriesReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/analytics/top-categories'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/analytics/top-categories?limit=168").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/analytics/top-categories
* Found 1 potential fault of type-code 101
*/
test("test_44_GetOnAnalyticsTop_categoriesReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/analytics/top-categories'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/analytics/top-categories").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/analytics/top-providers
* Found 1 potential fault of type-code 101
*/
test("test_45_GetOnTop_providersReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/analytics/top-providers'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/analytics/top-providers?limit=831").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/users/{id}
* Found 1 potential fault of type-code 101
*/
test("test_46_GetOnUserReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/users/{id}'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/users/JX_0").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/provider/bookings/{id}
* Found 1 potential fault of type-code 101
*/
test("test_47_GetOnProviderBookReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/provider/bookings/{id}'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/provider/bookings/498nkuv0RSjjrYF3").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/providers/{providerId}/reviews
* Found 1 potential fault of type-code 101
*/
test("test_48_GetOnProvidReviewsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/providers/{providerId}/reviews'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/providers/GYvGbXQnIX/reviews").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/providers/profile/me
* Found 1 potential fault of type-code 101
*/
test("test_49_GetOnMeReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/providers/profile/me'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/providers/profile/me").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/analytics/top-providers
* Found 1 potential fault of type-code 101
*/
test("test_50_GetOnAnalyticsTop_providersReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/analytics/top-providers'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/analytics/top-providers").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/analytics/bookings-over-time
* Found 1 potential fault of type-code 101
*/
test("test_51_GetOnBookings_over_timeReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/analytics/bookings-over-time'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/analytics/bookings-over-time?days=30").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/analytics/top-categories
* Found 1 potential fault of type-code 101
*/
test("test_52_GetOnTop_categoriesReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/analytics/top-categories'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/analytics/top-categories?limit=5").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/analytics/bookings-over-time
* Found 1 potential fault of type-code 101
*/
test("test_53_GetOnAnalyticsBookings_over_timeWithQueryparamNegativeDaysReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/analytics/bookings-over-time'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/analytics/bookings-over-time?days=-238689179").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/analytics/top-providers
* Found 1 potential fault of type-code 101
*/
test("test_54_GetOnAnalyticsTop_providersWithQueryparamNegativeLimitReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/analytics/top-providers'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/analytics/top-providers?limit=-549506656").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/analytics/top-providers
* Found 1 potential fault of type-code 101
*/
test("test_55_GetOnTop_providersReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/analytics/top-providers'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/analytics/top-providers?limit=5").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) GET:/api/admin/analytics/top-categories
* Found 1 potential fault of type-code 101
*/
test("test_56_GetOnAnalyticsTop_categoriesWithQueryparamNegativeLimitReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/analytics/top-categories'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/admin/analytics/top-categories?limit=-1849376082").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/bookings/{bookingId}/reviews
* Found 1 potential fault of type-code 101
*/
test("test_57_PostOnReviewsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/bookings/{bookingId}/reviews'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/bookings/1g6Iw5/reviews").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"rating\" : 2 " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/bookings/{id}/cancel
* Found 1 potential fault of type-code 101
*/
test("test_58_PostOnCancelReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/bookings/{id}/cancel'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/bookings/HLFtY3F7/cancel?reason=E").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/bookings/{id}/complete
* Found 1 potential fault of type-code 101
*/
test("test_59_PostOnCompleteReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/bookings/{id}/complete'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/bookings/bc2kx/complete").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/bookings/{id}/confirm
* Found 1 potential fault of type-code 101
*/
test("test_60_PostOnConfirmReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/bookings/{id}/confirm'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/bookings/Q4bVbrSgcGjp/confirm").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/notifications/{id}/read
* Found 1 potential fault of type-code 101
*/
test("test_61_PostOnReadReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/notifications/{id}/read'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/notifications/A9/read").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/bookings/{id}/cancel
* Found 1 potential fault of type-code 101
*/
test("test_62_PostOnCancelReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/bookings/{id}/cancel'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/bookings/0WL7Tv_YahA/cancel").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) PUT:/api/admin/categories/{id}
* Found 1 potential fault of type-code 101
*/
test("test_63_PutOnCategoriReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/categories/{id}'.
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/admin/categories/DW0FPp7HXeudaWq").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"name\" : \"lrv\", " + 
                " \"description\" : \"cg\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) PUT:/api/providers/listings/{id}
* Found 1 potential fault of type-code 101
*/
test("test_64_PutOnListReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/providers/listings/{id}'.
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/providers/listings/xrU").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"categoryId\" : \"9ueFMdtxQGtmtv\", " + 
                " \"title\" : \"ZLIN3o4L8hdRjnN\", " + 
                " \"description\" : \"aT0\", " + 
                " \"price\" : 2.6397139940606058E8 " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) PUT:/api/providers/profile/me
* Found 1 potential fault of type-code 101
*/
test("test_65_PutOnMeReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/providers/profile/me'.
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/providers/profile/me").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"displayName\" : \"AJNJBkeHOybXOB\", " + 
                " \"phone\" : \"N5r9LSD7mEAl\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) DELETE:/api/admin/reviews/{id}
* Found 1 potential fault of type-code 101
*/
test("test_66_DeleteOnAdminReviewReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/reviews/{id}'.
    const res_0 = await superagent
            .delete(baseUrlOfSut + "/api/admin/reviews/BLHUvT1bK9").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) DELETE:/api/admin/categories/{id}
* Found 1 potential fault of type-code 101
*/
test("test_67_DeleteOnCategoriReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/categories/{id}'.
    const res_0 = await superagent
            .delete(baseUrlOfSut + "/api/admin/categories/P2SnckDp4mEumK6U").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) DELETE:/api/providers/listings/{id}
* Found 1 potential fault of type-code 101
*/
test("test_68_DeleteOnListReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/providers/listings/{id}'.
    const res_0 = await superagent
            .delete(baseUrlOfSut + "/api/providers/listings/5_COo").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (404) GET:/api/providers/{providerId}/profile
* Found 1 potential fault of type-code 101
*/
test("test_69_GetOnProfileReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/api/providers/{providerId}/profile'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/providers/XHrn2fUtB/profile").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(404);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.message).toBe("Provider profile not found");
    expect(res_0.body.data).toBe(null);
});


/**
* Calls:
* (403) POST:/api/admin/bookings/{id}/cancel
* Found 1 potential fault of type-code 101
*/
test("test_70_PostOnCancelReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/bookings/{id}/cancel'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/admin/bookings/kaqc4y6iB/cancel?reason=PUID").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/providers/listings/{id}/photos
* Found 1 potential fault of type-code 101
*/
test("test_71_PostOnListPhotosReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/providers/listings/{id}/photos'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/providers/listings/mW7GpvSpZ/photos").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"file\" : \"V5snN8xX8F3pAH\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/providers/listings/{id}/photos
* Found 1 potential fault of type-code 101
*/
test("test_72_PostOnListPhotosWithQueryparamReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/providers/listings/{id}/photos'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/providers/listings/I7onqLWGtdlxP7g7/photos?caption=wt1coQ27S2").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"file\" : \"UaZfdl87ZsT8YF\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) POST:/api/admin/bookings/{id}/cancel
* Found 1 potential fault of type-code 101
*/
test("test_73_PostOnCancelReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/bookings/{id}/cancel'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/admin/bookings/lK3sl/cancel").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) PATCH:/api/admin/listings/{id}/status
* Found 1 potential fault of type-code 101
*/
test("test_74_PatchOnListStatusWithQueryparamIsactiveReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/listings/{id}/status'.
    const res_0 = await superagent
            .patch(baseUrlOfSut + "/api/admin/listings/IDBsWGgl/status?isActive=true").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) PATCH:/api/admin/users/{id}/status
* Found 1 potential fault of type-code 101
*/
test("test_75_PatchOnUserStatusWithQueryparamReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/users/{id}/status'.
    const res_0 = await superagent
            .patch(baseUrlOfSut + "/api/admin/users/jlYwf17/status?isActive=false").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) PATCH:/api/admin/listings/{id}/status
* Found 1 potential fault of type-code 101
*/
test("test_76_PatchOnListStatusWithQueryparamReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/listings/{id}/status'.
    const res_0 = await superagent
            .patch(baseUrlOfSut + "/api/admin/listings/KkafhBMZs/status?isActive=false").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) PATCH:/api/admin/users/{id}/status
* Found 1 potential fault of type-code 101
*/
test("test_77_PatchOnUserStatusWithQueryparamIsactiveReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/admin/users/{id}/status'.
    const res_0 = await superagent
            .patch(baseUrlOfSut + "/api/admin/users/b8Fwq7kwHHTu/status?isActive=true").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (403) DELETE:/api/providers/listings/{id}/photos/{photoId}
* Found 1 potential fault of type-code 101
*/
test("test_78_DeleteOnPhotoReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/api/providers/listings/{id}/photos/{photoId}'.
    const res_0 = await superagent
            .delete(baseUrlOfSut + "/api/providers/listings/TH/photos/KKwivws0E1").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});
