/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
const superagent = require("superagent");
const EM = require("./EMTestUtils.js");
jest.setTimeout(60000);




/**
*  This file was automatically generated by EvoMaster on 2026-05-13T21:45:50.812069+05:30[Asia/Kolkata]
*  
*  The generated test suite contains 13 tests
*  
*  Covered targets: 40
*  
*  Used time: 0h 2m 0s
*  
*  Needed budget for current results: 30%
*  
*  This file contains test cases that represent successful calls.
*  
*/

const baseUrlOfSut = "http://localhost:8083";


beforeAll( async () => {
});








/**
* Calls:
* (200) GET:/api/categories
*/
test("test_0_GetOnCategoriesReturnsEmptyList", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/categories").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.length).toBe(0);
});


/**
* Calls:
* (200) GET:/api/listings
*/
test("test_1_GetOnApiListingsWithQueryparamReturnsEmptyList", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/listings?categoryId=bcGVVJspq").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.length).toBe(0);
});


/**
* Calls:
* (200) GET:/api/listings
*/
test("test_2_GetOnApiListingsReturnsEmptyList", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/listings").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.length).toBe(0);
});


/**
* Calls:
* (200) GET:/api/test/get_T
*/
test("test_3_GetOnGet_tReturnsEmptyObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/test/get_T").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(Object.keys(res_0.body).length).toBe(0);
});


/**
* Calls:
* (200) POST:/api/test/reset
*/
test("test_4_PostOnResetReturns200", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/test/reset").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.status).toBe("reset");
});


/**
* Calls:
* (200) OPTIONS:/api/test/reset
*/
test("test_5_OptionsOnResetReturns200", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/test/reset").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    // expect(res_0.header["allow"].startsWith("POST,OPTIONS")).toBe(true);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (200) OPTIONS:/api/test/register
*/
test("test_6_OptionsOnRegisterReturns200", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/test/register").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    // expect(res_0.header["allow"].startsWith("POST,OPTIONS")).toBe(true);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (200) OPTIONS:/api/auth/signup
*/
test("test_7_OptionsOnSignupReturns200", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/auth/signup").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    // expect(res_0.header["allow"].startsWith("POST,OPTIONS")).toBe(true);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (200) OPTIONS:/api/auth/logout
*/
test("test_8_OptionsOnLogoutReturns200", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/auth/logout").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    // expect(res_0.header["allow"].startsWith("POST,OPTIONS")).toBe(true);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (200) OPTIONS:/api/auth/login
*/
test("test_9_OptionsOnAuthLoginReturns200", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/auth/login").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    // expect(res_0.header["allow"].startsWith("POST,OPTIONS")).toBe(true);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (200) OPTIONS:/api/test/get_T
*/
test("test_10_OptionsOnGet_tReturns200", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/test/get_T").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    // expect(res_0.header["allow"].startsWith("HEAD,GET,OPTIONS")).toBe(true);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (200) GET:/api/listings/{listingId}/reviews
*/
test("test_11_GetOnReviewsReturnsEmptyList", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/listings/pOk7R/reviews").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.length).toBe(0);
});


/**
* Calls:
* (200) OPTIONS:/api/auth/admin/login
*/
test("test_12_OptionsOnAdminLoginReturns200", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/auth/admin/login").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    // expect(res_0.header["allow"].startsWith("POST,OPTIONS")).toBe(true);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});
