/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
const superagent = require("superagent");
const EM = require("./EMTestUtils.js");
jest.setTimeout(60000);




/**
*  This file was automatically generated by EvoMaster on 2026-05-13T21:34:07.765970+05:30[Asia/Kolkata]
*  
*  The generated test suite contains 24 tests
*  
*  Covered targets: 50
*  
*  Used time: 0h 2m 0s
*  
*  Needed budget for current results: 23%
*  
*  This file contains test cases that represent failed calls, but not indicative of faults.
*  
*/

const baseUrlOfSut = "http://localhost:5002";


beforeAll( async () => {
});








/**
* Calls:
* (401) GET:/api/orders
*/
test("test_0_GetOnApiOrdersReturns401", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/orders").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) GET:/api/cart
*/
test("test_1_GetOnCartReturns401", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/cart").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) POST:/api/reviews
*/
test("test_2_PostOnReviewsReturns401", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/reviews").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) POST:/api/restaurants
*/
test("test_3_PostOnRestaurantsReturns401", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/restaurants").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) POST:/api/orders
*/
test("test_4_PostOnOrdersReturns401", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/orders").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) POST:/api/menu
*/
test("test_5_PostOnMenuReturns401", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/menu").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) POST:/api/cart
*/
test("test_6_PostOnCartReturns401", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/cart").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (400) POST:/api/auth/login
*/
test("test_7_PostOnLoginReturns400", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/auth/login").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(400);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("\"email\" is required");
});


/**
* Calls:
* (400) POST:/api/auth/register
*/
test("test_8_PostOnRegisterReturns400", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/auth/register").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"fullName\" : \"33Sh8v_sNTU5n\", " + 
                " \"mobile\" : \"K\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(400);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("\"email\" is required");
});


/**
* Calls:
* (401) GET:/api/users/me
*/
test("test_9_GetOnMeReturns401", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/users/me").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) GET:/api/orders/{id}
*/
test("test_10_GetOnOrderReturns401", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/orders/dG9Yi2WX1DO").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) GET:/api/agents/available
*/
test("test_11_GetOnAvailableReturns401", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/agents/available").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) PUT:/api/users/me
*/
test("test_12_PutOnMeReturns401", async () => {
    
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/users/me").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) PUT:/api/restaurants/{id}
*/
test("test_13_PutOnRestaurReturns401", async () => {
    
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/restaurants/Bxk6Vt").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) PUT:/api/menu/{id}
*/
test("test_14_PutOnMenuReturns401", async () => {
    
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/menu/8_0B5HALvIsmCsR").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) PUT:/api/cart/{itemId}
*/
test("test_15_PutOnCartReturns401", async () => {
    
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/cart/xLi7M1Him8Srga_F").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) DELETE:/api/menu/{id}
*/
test("test_16_DeleteOnMenuReturns401", async () => {
    
    const res_0 = await superagent
            .delete(baseUrlOfSut + "/api/menu/qg").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) DELETE:/api/cart/clear
*/
test("test_17_DeleteOnClearReturns401", async () => {
    
    const res_0 = await superagent
            .delete(baseUrlOfSut + "/api/cart/clear").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) DELETE:/api/cart/{itemId}
*/
test("test_18_DeleteOnCartReturns401", async () => {
    
    const res_0 = await superagent
            .delete(baseUrlOfSut + "/api/cart/Bk1kMYtxA").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (404) GET:/api/restaurants/{id}
*/
test("test_19_GetOnRestaurReturns404", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/restaurants/6bQWmMRIf8Ot").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(404);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Restaurant not found");
});


/**
* Calls:
* (401) GET:/api/agents/me/orders
*/
test("test_20_GetOnMeOrdersReturns401", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/agents/me/orders").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) PUT:/api/orders/{id}/assign
*/
test("test_21_PutOnAssignReturns401", async () => {
    
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/orders/VIBUwXENfsgw2ke2/assign").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) PUT:/api/orders/{id}/status
*/
test("test_22_PutOnOrderStatusReturns401", async () => {
    
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/orders/b/status").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});


/**
* Calls:
* (401) PUT:/api/agents/me/status
*/
test("test_23_PutOnMeStatusReturns401", async () => {
    
    const res_0 = await superagent
            .put(baseUrlOfSut + "/api/agents/me/status").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Access denied. No token provided.");
});
