/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
const superagent = require("superagent");
const EM = require("./EMTestUtils.js");
jest.setTimeout(60000);




/**
*  This file was automatically generated by EvoMaster on 2026-05-13T21:34:07.753738+05:30[Asia/Kolkata]
*  
*  The generated test suite contains 3 tests
*  
*  Covered targets: 12
*  
*  Used time: 0h 2m 0s
*  
*  Needed budget for current results: 23%
*  
*  This file contains test cases that are likely to indicate faults.
*  
*/

const baseUrlOfSut = "http://localhost:5002";


beforeAll( async () => {
});








/**
* Calls:
* (500) GET:/api/restaurants/{id}
* Found 1 potential fault of type-code 100
*/
test("test_0_GetOnApiRestaurCauses500_internalservererror", async () => {
    
    // Fault100. HTTP Status 500.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/restaurants/dxNFvQy").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(500);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Cast to ObjectId failed for value \"dxNFvQy\" (type string) at path \"_id\" for model \"Restaurant\"");
});


/**
* Calls:
* (500) GET:/api/reviews/restaurant/{restaurantId}
* Found 1 potential fault of type-code 100
*/
test("test_1_GetOnReviewsRestaurCauses500_internalservererror", async () => {
    
    // Fault100. HTTP Status 500.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/reviews/restaurant/f2").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(500);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Cast to ObjectId failed for value \"f2\" (type string) at path \"restaurant\" for model \"Review\"");
});


/**
* Calls:
* (500) GET:/api/restaurants/{id}/menu
* Found 1 potential fault of type-code 100
*/
test("test_2_GetOnMenuCauses500_internalservererror", async () => {
    
    // Fault100. HTTP Status 500.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/restaurants/6tHoZ8J316Q/menu").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(500);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Cast to ObjectId failed for value \"6tHoZ8J316Q\" (type string) at path \"restaurant\" for model \"MenuItem\"");
});
