/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
const superagent = require("superagent");
const EM = require("./EMTestUtils.js");
jest.setTimeout(60000);




/**
*  This file was automatically generated by EvoMaster on 2026-05-13T21:34:07.760440+05:30[Asia/Kolkata]
*  
*  The generated test suite contains 25 tests
*  
*  Covered targets: 85
*  
*  Used time: 0h 2m 0s
*  
*  Needed budget for current results: 23%
*  
*  This file contains test cases that represent successful calls.
*  
*/

const baseUrlOfSut = "http://localhost:5002";


beforeAll( async () => {
});








/**
* Calls:
* (200) GET:/api/restaurants
*/
test("test_0_GetOnApiRestaurantsWithQueryparamsReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/restaurants?" + 
                "cuisine=O5&" + 
                "isOpen=false").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.restaurants.length).toBe(0);
    expect(res_0.body.pagination.current).toBe(1);
    expect(res_0.body.pagination.pages).toBe(0);
    expect(res_0.body.pagination.total).toBe(0);
});


/**
* Calls:
* (200) GET:/api/restaurants
*/
test("test_1_GetOnApiRestaurantsWithQueryparamsIsopenReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/restaurants?" + 
                "city=8n8ljo2o&" + 
                "isOpen=true").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.restaurants.length).toBe(0);
    expect(res_0.body.pagination.current).toBe(1);
    expect(res_0.body.pagination.pages).toBe(0);
    expect(res_0.body.pagination.total).toBe(0);
});


/**
* Calls:
* (200) GET:/api/restaurants
*/
test("test_2_GetOnApiRestaurantsWithQueryparamReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/restaurants?cuisine=vM4LC").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.restaurants.length).toBe(0);
    expect(res_0.body.pagination.current).toBe(1);
    expect(res_0.body.pagination.pages).toBe(0);
    expect(res_0.body.pagination.total).toBe(0);
});


/**
* Calls:
* (204) OPTIONS:/api/cart
*/
test("test_3_OptionsOnCartReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/cart").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/menu
*/
test("test_4_OptionsOnMenuReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/menu").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/orders
*/
test("test_5_OptionsOnApiOrdersReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/orders").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/restaurants
*/
test("test_6_OptionsOnRestaurantsReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/restaurants").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/reviews
*/
test("test_7_OptionsOnReviewsReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/reviews").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/agents/available
*/
test("test_8_OptionsOnAvailableReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/agents/available").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/auth/register
*/
test("test_9_OptionsOnRegisterReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/auth/register").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/auth/login
*/
test("test_10_OptionsOnLoginReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/auth/login").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/cart/{itemId}
*/
test("test_11_OptionsOnCartReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/cart/i7vgY0mJ4").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/cart/clear
*/
test("test_12_OptionsOnClearReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/cart/clear").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/menu/{id}
*/
test("test_13_OptionsOnMenuReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/menu/dihWNZP_QYT").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/orders/{id}
*/
test("test_14_OptionsOnOrderReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/orders/BFqDhOJ4I5Ij").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/restaurants/{id}
*/
test("test_15_OptionsOnApiRestaurReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/restaurants/FPrZZGfxIarecf").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/users/me
*/
test("test_16_OptionsOnMeReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/users/me").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (200) GET:/api/reviews/restaurant/{restaurantId}
*/
test("test_17_GetOnRestaurReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/reviews/restaurant/5cXSernOaqUb").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.reviews.length).toBe(0);
    expect(res_0.body.pagination.current).toBe(1);
    expect(res_0.body.pagination.pages).toBe(0);
    expect(res_0.body.pagination.total).toBe(0);
});


/**
* Calls:
* (200) GET:/api/restaurants/{id}/menu
*/
test("test_18_GetOnMenuReturnsEmptyList", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/restaurants/0Qvf6K2L8a8l/menu").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.length).toBe(0);
});


/**
* Calls:
* (204) OPTIONS:/api/agents/me/orders
*/
test("test_19_OptionsOnMeOrdersReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/agents/me/orders").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/agents/me/status
*/
test("test_20_OptionsOnMeStatusReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/agents/me/status").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/orders/{id}/status
*/
test("test_21_OptionsOnOrderStatusReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/orders/1/status").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/orders/{id}/assign
*/
test("test_22_OptionsOnAssignReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/orders/Hce6VH/assign").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/restaurants/{id}/menu
*/
test("test_23_OptionsOnRestaurMenuReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/restaurants/Gl/menu").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/reviews/restaurant/{restaurantId}
*/
test("test_24_OptionsOnReviewsRestaurReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/reviews/restaurant/VJqsfFf31n").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});
