/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
const superagent = require("superagent");
const EM = require("./EMTestUtils.js");
jest.setTimeout(60000);




/**
*  This file was automatically generated by EvoMaster on 2026-05-13T21:49:45.185499+05:30[Asia/Kolkata]
*  
*  The generated test suite contains 16 tests
*  
*  Covered targets: 62
*  
*  Used time: 0h 1m 1s
*  
*  Needed budget for current results: 29%
*  
*  This file contains test cases that are likely to indicate faults.
*  
*/

const baseUrlOfSut = "http://localhost:4002";


beforeAll( async () => {
});








/**
* Calls:
* (500) POST:/app/resend-otp
* Found 2 potential faults. Type-codes: 100, 101
*/
test("test_0_PostOnResend_otpShowsfaults_100_101", async () => {
    
    // Fault100. HTTP Status 500.
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/app/resend-otp'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/app/resend-otp").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .ok(res => res.status);
    
    expect(res_0.status).toBe(500);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Internal server error");
});


/**
* Calls:
* (500) POST:/app/verify-password
* Found 2 potential faults. Type-codes: 100, 101
*/
test("test_1_PostOnVerify_passwordShowsfaults_100_101", async () => {
    
    // Fault100. HTTP Status 500.
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/app/verify-password'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/app/verify-password").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"deviceId\" : \"p8SApVu6O\", " + 
                " \"password\" : \"RG4Bjoq2\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(500);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Internal server error");
});


/**
* Calls:
* (500) POST:/app/check-user
* Found 2 potential faults. Type-codes: 100, 101
*/
test("test_2_PostOnCheck_userShowsfaults_100_101", async () => {
    
    // Fault100. HTTP Status 500.
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/app/check-user'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/app/check-user").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .ok(res => res.status);
    
    expect(res_0.status).toBe(500);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Internal server error");
});


/**
* Calls:
* (400) POST:/app/verify-otp
* Found 1 potential fault of type-code 101
*/
test("test_3_PostOnVerify_otpReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/app/verify-otp'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/app/verify-otp").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .ok(res => res.status);
    
    expect(res_0.status).toBe(400);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Invalid OTP");
});


/**
* Calls:
* (401) GET:/sessions/get-sessions
* Found 1 potential fault of type-code 101
*/
test("test_4_GetOnGet_sessionsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/sessions/get-sessions'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/sessions/get-sessions").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) GET:/devices/{deviceId}
* Found 1 potential fault of type-code 101
*/
test("test_5_GetOnDevicReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/devices/{deviceId}'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/devices/yB7hrHSR3Xl2").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) GET:/devices/other
* Found 1 potential fault of type-code 101
*/
test("test_6_GetOnOtherReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/devices/other'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/devices/other").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) GET:/devices/my
* Found 1 potential fault of type-code 101
*/
test("test_7_GetOnMyReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/devices/my'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/devices/my").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) POST:/sessions/join
* Found 1 potential fault of type-code 101
*/
test("test_8_PostOnJoinReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/sessions/join'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/sessions/join").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) POST:/sessions/create
* Found 1 potential fault of type-code 101
*/
test("test_9_PostOnCreateReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/sessions/create'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/sessions/create").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) DELETE:/sessions/{sessionKey}
* Found 1 potential fault of type-code 101
*/
test("test_10_DeleteOnSessionReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/sessions/{sessionKey}'.
    const res_0 = await superagent
            .delete(baseUrlOfSut + "/sessions/81yTAr1XN").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) DELETE:/devices/{deviceId}
* Found 1 potential fault of type-code 101
*/
test("test_11_DeleteOnDevicReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/devices/{deviceId}'.
    const res_0 = await superagent
            .delete(baseUrlOfSut + "/devices/9gHEwioj").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (404) POST:/app/logout-app
* Found 1 potential fault of type-code 101
*/
test("test_12_PostOnLogout_appReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/app/logout-app'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/app/logout-app").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"deviceId\" : \"SnV0KV0KAaiR_e5r\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(404);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Device not found");
});


/**
* Calls:
* (404) POST:/app/get-user-data
* Found 1 potential fault of type-code 101
*/
test("test_13_PostOnGet_user_dataReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/app/get-user-data'.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/app/get-user-data").set('Accept', "*/*")
            .set('Content-Type','application/json')
            .ok(res => res.status);
    
    expect(res_0.status).toBe(404);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.type).toBe("deleted");
    expect(res_0.body.message).toBe("Device not found");
});


/**
* Calls:
* (401) GET:/sessions/connected-sessions/{deviceId}
* Found 1 potential fault of type-code 101
*/
test("test_14_GetOnConnected_sessReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/sessions/connected-sessions/{deviceId}'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/sessions/connected-sessions/bGEPi6pHyjYeCS").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Unauthorized");
});


/**
* Calls:
* (401) GET:/devices/{deviceId}/get-uploads
* Found 1 potential fault of type-code 101
*/
test("test_15_GetOnGet_uploadsReturnsmismatchresponsewithschema", async () => {
    
    // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/devices/{deviceId}/get-uploads'.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/devices/VppIbuXMx2anN5Gg/get-uploads").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(401);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.message).toBe("Unauthorized");
});
