/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
const superagent = require("superagent");
const EM = require("./EMTestUtils.js");
jest.setTimeout(60000);




/**
*  This file was automatically generated by EvoMaster on 2026-05-13T21:49:45.203456+05:30[Asia/Kolkata]
*  
*  The generated test suite contains 15 tests
*  
*  Covered targets: 45
*  
*  Used time: 0h 1m 1s
*  
*  Needed budget for current results: 29%
*  
*  This file contains test cases that represent successful calls.
*  
*/

const baseUrlOfSut = "http://localhost:4002";


beforeAll( async () => {
});








/**
* Calls:
* (204) OPTIONS:/app/get-user-data
*/
test("test_0_OptionsOnGet_user_dataReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/app/get-user-data").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/app/check-user
*/
test("test_1_OptionsOnCheck_userReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/app/check-user").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/app/verify-otp
*/
test("test_2_OptionsOnVerify_otpReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/app/verify-otp").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/app/verify-password
*/
test("test_3_OptionsOnVerify_passwordReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/app/verify-password").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/app/resend-otp
*/
test("test_4_OptionsOnResend_otpReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/app/resend-otp").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/app/logout-app
*/
test("test_5_OptionsOnLogout_appReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/app/logout-app").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/devices/my
*/
test("test_6_OptionsOnMyReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/devices/my").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/devices/other
*/
test("test_7_OptionsOnOtherReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/devices/other").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/devices/{deviceId}
*/
test("test_8_OptionsOnDevicReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/devices/hpPieB796CVCO").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/sessions/create
*/
test("test_9_OptionsOnCreateReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/sessions/create").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/sessions/join
*/
test("test_10_OptionsOnJoinReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/sessions/join").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/sessions/get-sessions
*/
test("test_11_OptionsOnGet_sessionsReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/sessions/get-sessions").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/sessions/{sessionKey}
*/
test("test_12_OptionsOnSessionReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/sessions/Yk").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/devices/{deviceId}/get-uploads
*/
test("test_13_OptionsOnGet_uploadsReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/devices/nTk_Rcb0IS6kSZB3/get-uploads").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/sessions/connected-sessions/{deviceId}
*/
test("test_14_OptionsOnConnected_sessReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/sessions/connected-sessions/KAvqZKyVexlzSW").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});
